**Pandas :** Pandas is a python libray for data manipulation and analysis.

> Thinks of it as **"Excel for Python"** - which helps to load, clean, filter, sort and analyze data using tables called DataFrames.

**Why pandas?**
* Fast - handles millions of rows easily.
* Simple - readable, clean syntax.
* Flexible - works with CSV, Excel, JSON, SQL and  More.
* Powerful - built-in tools for cleaning, grouping, merging data.
* Popular - used in data science, ML, finance, research everywhere.
* Built on NumPy - so, it's numerically every efficient.

**📚 Pandas Full Learning Path :**

1. Series          → 1D data (like a single column)
2. DataFrame       → 2D table (rows + columns)
3. Reading Data    → CSV, Excel, JSON, SQL
4. Exploring Data  → head(), tail(), info(), describe()
5. Selecting Data  → columns, rows, loc, iloc
6. Filtering       → condition-based row selection
7. Cleaning Data   → null values, duplicates, data types
8. Sorting         → sort_values(), sort_index()
9. Grouping        → groupby()
10. Merging        → merge(), concat(), join()
11. Apply/Map      → apply(), map(), lambda
12. Time Series    → date-based analysis
13. Export Data    → to_csv(), to_excel()

**Before Start:** Import pandas libaray:

In [137]:
import pandas as pd

**1. Serise (One-Dimensional Data) :**   One column

**Create one column:**

In [138]:
Score = pd.Series([85, 90, 78, 92, 88, 70, 95, 80, 73, 91])
print(Score)

0    85
1    90
2    78
3    92
4    88
5    70
6    95
7    80
8    73
9    91
dtype: int64

**2. DataFrame (Two-Dimensional Data) :** Full Excel (Column & Row)

**Required another column for two-dimensional data:**

In [139]:
Name = pd.Series(["Ali", "Bob", "Sara", "John", "Mia",  "Tom", "Emma", "Ray", "Nina", "Leo"])
print(Name)

0     Ali
1     Bob
2    Sara
3    John
4     Mia
5     Tom
6    Emma
7     Ray
8    Nina
9     Leo
dtype: str

**One-way of creating DataFrame :**

In [140]:
df = pd.DataFrame({
      "Name" : Name,
      "Score" : Score
})
print(df)

   Name  Score
0   Ali     85
1   Bob     90
2  Sara     78
3  John     92
4   Mia     88
5   Tom     70
6  Emma     95
7   Ray     80
8  Nina     73
9   Leo     91

**Another-way of creating DataFrame :**

In [141]:
df = pd.DataFrame({
          "Age" : ["M", "M", "F", "M", "F", "M", "F", "M", "F", "M"],
          "Department" : ["CSE", "BBA", "CSE", "EEE", "BBA", "CSE", "EEE", "BBA", "EEE", "CSE"]  
})
df

  Age Department
0   M        CSE
1   M        BBA
2   F        CSE
3   M        EEE
4   F        BBA
5   M        CSE
6   F        EEE
7   M        BBA
8   F        EEE
9   M        CSE

**3. Reading Data :** Load data from different file formats:

           pd.read_csv()
           pd.read_excel()
           pd.read_json()
           pd.read_sql()

In [142]:
df = pd.read_csv('students.csv')
df

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
5,106,Tom Hasan,M,26,Dhaka,CSE,70,C,5000,True,2022-01-15,NaN,72,1766666666,tom@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80.0,80,1788888888,ray@gmail.com
8,109,Nina Begum,F,24,Dhaka,EEE,73,C,7000,True,2022-03-10,NaN,78,1799999999,nina@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,93.0,96,1700000000,leo@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,70.0,65,1711100001,riya@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,NaN,80,1733300003,priya@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,NaN,70,1766600006,arif@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,79.0,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

**4. Explore Data :** Quickly understand your data :

       df.head()
       df.tail()
       df.info()
       df.describe()
       df.shape
       df.columns
       df.dtype
       df.isnull().sum()
       df.notnull().sum()
       df.duplicated().sum()
       df.value_counts()
       df.nunique()
       df.sample()
       df.memory_usage()
       df.count()
       len(df)

**a. Print first 5 rows:**

In [143]:
df.head()

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com

**b. Print last 5 rows:**

In [144]:
df.tail()

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,NaN,70,1766600006,arif@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,79.0,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

**c. Summary info:**

In [145]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   20 non-null     int64
 1   Name        20 non-null     str
 2   Gender      20 non-null     str
 3   Age         20 non-null     int64
 4   City        20 non-null     str
 5   Department  20 non-null     str
 6   Score       20 non-null     int64
 7   Grade       20 non-null     str
 8   Fee         20 non-null     int64
 9   Paid        20 non-null     bool
 10  JoinDate    20 non-null     str
 11  Marks       15 non-null     float64
 12  Attendance  20 non-null     int64
 13  Phone       20 non-null     int64
 14  Email       20 non-null     str
dtypes: bool(1), float64(1), int64(6), str(7)
memory usage: 2.3 KB

**d. Statistical Summary of Numerical Columns :**

In [146]:
df.describe()

,StudentID,Age,Score,Fee,Marks,Attendance,Phone
count,20.00000,20.000000,20.000000,20.000000,15.000000,20.000000,2.000000e+01
mean,110.50000,23.500000,83.250000,5950.000000,88.333333,86.350000,1.749975e+09
std,5.91608,1.732051,8.961174,825.577947,7.584445,10.327658,3.272696e+07
min,101.00000,21.000000,67.000000,5000.000000,70.000000,65.000000,1.700000e+09
25%,105.75000,22.000000,76.750000,5000.000000,84.500000,79.500000,1.722217e+09
50%,110.50000,23.000000,85.500000,6000.000000,90.000000,88.500000,1.749972e+09
75%,115.25000,25.000000,91.000000,7000.000000,94.000000,95.250000,1.777719e+09
max,120.00000,27.000000,95.000000,7000.000000,97.000000,99.000000,1.800000e+09

**d. Total Rows & Columns :**

In [147]:
df.shape

(20, 15)

**e. Columns Name :**

In [148]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'Age', 'City', 'Department', 'Score',
       'Grade', 'Fee', 'Paid', 'JoinDate', 'Marks', 'Attendance', 'Phone',
       'Email'],
      dtype='str')

**f. Data type of columns:**

In [149]:
df.dtypes

StudentID       int64
Name              str
Gender            str
Age             int64
City              str
Department        str
Score           int64
Grade             str
Fee             int64
Paid             bool
JoinDate          str
Marks         float64
Attendance      int64
Phone           int64
Email             str
dtype: object

**g. Check total null :**

In [150]:
df.isnull().sum()

StudentID     0
Name          0
Gender        0
Age           0
City          0
Department    0
Score         0
Grade         0
Fee           0
Paid          0
JoinDate      0
Marks         5
Attendance    0
Phone         0
Email         0
dtype: int64

**h. Check total data:**

In [151]:
df.notnull().sum()

StudentID     20
Name          20
Gender        20
Age           20
City          20
Department    20
Score         20
Grade         20
Fee           20
Paid          20
JoinDate      20
Marks         15
Attendance    20
Phone         20
Email         20
dtype: int64

**i. Check total duplicate rows :**

In [152]:
df.duplicated().sum()

np.int64(0)

**j. How many times each value appears :**

In [153]:
df.value_counts()

StudentID  Name           Gender  Age  City    Department  Score  Grade  Fee   Paid   JoinDate    Marks  Attendance  Phone       Email
101        Ali Ahmed      M       22   Dhaka   CSE         85     B      5000  True   2022-01-15  88.0   90          1711111111  ali@gmail.com       1
102        Bob Khan       M       25   London  BBA         90     A      6000  True   2021-06-20  92.0   95          1722222222  bob@gmail.com       1
104        John Doe       M       24   Paris   EEE         92     A      7000  True   2020-09-01  95.0   98          1744444444  john@gmail.com      1
105        Mia Rahman     F       22   London  BBA         88     B      6000  False  2021-11-25  85.0   88          1755555555  mia@gmail.com       1
107        Emma Akter     F       23   Paris   EEE         95     A      7000  True   2020-09-01  97.0   99          1777777777  emma@gmail.com      1
108        Ray Molla      M       25   London  BBA         80     B      6000  False  2021-06-20  80.0   80          1788888888  ray@gmail.com       1
110        Leo Chowdhury  M       22   Paris   CSE         91     A      5000  True   2020-09-01  93.0   96          1700000000  leo@gmail.com       1
111        Riya Sen       F       21   Dhaka   BBA         67     C      6000  False  2023-01-10  70.0   65          1711100001  riya@gmail.com      1
112        Karim Uddin    M       27   Paris   EEE         88     B      7000  True   2019-08-15  90.0   91          1722200002  karim@gmail.com     1
114        Nabil Islam    M       24   Dhaka   BBA         94     A      6000  True   2021-03-05  96.0   97          1744400004  nabil@gmail.com     1
115        Sadia Khatun   F       23   Paris   CSE         82     B      5000  False  2022-09-12  84.0   87          1755500005  sadia@gmail.com     1
117        Tania Akter    F       22   Dhaka   BBA         91     A      6000  True   2022-02-28  93.0   94          1777700007  tania@gmail.com     1
118        Rakib Hassan   M       23   Paris   CSE         77     C      5000  False  2022-11-01  79.0   75          1788800008  rakib@gmail.com     1
119        Faria Noor     F       26   London  EEE         86     B      7000  True   2020-04-14  88.0   89          1799900009  faria@gmail.com     1
120        Sabbir Ahmed   M       21   Dhaka   BBA         93     A      6000  True   2023-03-22  95.0   98          1700000010  sabbir@gmail.com    1
Name: count, dtype: int64

**Checking specific column:**

In [154]:
df['Department'].value_counts()

Department
CSE    7
BBA    7
EEE    6
Name: count, dtype: int64

**k. Count unique values in each column:**

In [155]:
df.nunique()

StudentID     20
Name          20
Gender         2
Age            7
City           3
Department     3
Score         18
Grade          3
Fee            3
Paid           2
JoinDate      15
Marks         12
Attendance    18
Phone         20
Email         20
dtype: int64

**l. Show random rows:**

In [156]:
df.sample(5)

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com
5,106,Tom Hasan,M,26,Dhaka,CSE,70,C,5000,True,2022-01-15,NaN,72,1766666666,tom@gmail.com

**m. Ram Usage of each Column:**

In [157]:
df.memory_usage()

Index         132
StudentID     160
Name          160
Gender        160
Age           160
City          160
Department    160
Score         160
Grade         160
Fee           160
Paid           20
JoinDate      160
Marks         160
Attendance    160
Phone         160
Email         160
dtype: int64

**n. Non-null count of each column :**

In [158]:
df.count()

StudentID     20
Name          20
Gender        20
Age           20
City          20
Department    20
Score         20
Grade         20
Fee           20
Paid          20
JoinDate      20
Marks         15
Attendance    20
Phone         20
Email         20
dtype: int64

**o. Total number of rows:**

In [159]:
len(df)

20

**5. Selecting Data :**  columns, rows, loc, iloc, at, iat, set_index
          
          * single column               ->  ["col"]	
          * Multiple columns            ->  ["col1", "col2"]         
          * Select by label/name        ->  .loc[]
          * select by position number   ->  .iloc[]

          
          * label	single fast value     ->  .at[]
          * position	single fast value ->  .iat[]
          * setting index               ->  .set_index

**a. Selecting single column:**

In [160]:
df['Name']

0         Ali Ahmed
1          Bob Khan
2        Sara Islam
3          John Doe
4        Mia Rahman
5         Tom Hasan
6        Emma Akter
7         Ray Molla
8        Nina Begum
9     Leo Chowdhury
10         Riya Sen
11      Karim Uddin
12        Priya Das
13      Nabil Islam
14     Sadia Khatun
15     Arif Hossain
16      Tania Akter
17     Rakib Hassan
18       Faria Noor
19     Sabbir Ahmed
Name: Name, dtype: str

**b. Selecting multiple column:**

In [161]:
df[['Name', 'Score']]

             Name  Score
0       Ali Ahmed     85
1        Bob Khan     90
2      Sara Islam     78
3        John Doe     92
4      Mia Rahman     88
5       Tom Hasan     70
6      Emma Akter     95
7       Ray Molla     80
8      Nina Begum     73
9   Leo Chowdhury     91
10       Riya Sen     67
11    Karim Uddin     88
12      Priya Das     76
13    Nabil Islam     94
14   Sadia Khatun     82
15   Arif Hossain     69
16    Tania Akter     91
17   Rakib Hassan     77
18     Faria Noor     86
19   Sabbir Ahmed     93

**c. Selecting Rows :**

position-based slicing, end excluded → only row 0

In [162]:
df[:1]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com

In [163]:
df[0:5]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com

**d. Label-based selection :**  Syntax -> df.loc[row_label, column_label]

**Single row with specific column:**

label-based slicing, end included → row 0 and 1

In [164]:
df.loc[:1]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com

**Specific columns:**

In [165]:
df.loc[0:2, ['Name', 'Score']]

         Name  Score
0   Ali Ahmed     85
1    Bob Khan     90
2  Sara Islam     78

**e. Position-based selection:** Use index position.

 Syntex-> df.iloc[row_index, column_index]

**single row & column:**

In [166]:
df.iloc[0,1]

'Ali Ahmed'

**Multiple rows & columns:**

In [167]:
df.iloc[0:2, 0:2]

   StudentID       Name
0        101  Ali Ahmed
1        102   Bob Khan

**f. Selecting Specific Values:**

With specific label:

In [168]:
df.at[0, 'Score']

np.int64(85)

With specific position :

In [169]:
df.iat[0,1]

'Ali Ahmed'

**6. Filtering →** showing only rows that match a condition.

**a. Boolean Selection:**

In [170]:
df[df['Score'] > 80]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,93.0,96,1700000000,leo@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

**b. Selecting With conditions and loc:**

In [171]:
df.loc[df['Score'] > 80, ['Name']]

             Name
0       Ali Ahmed
1        Bob Khan
3        John Doe
4      Mia Rahman
6      Emma Akter
9   Leo Chowdhury
11    Karim Uddin
13    Nabil Islam
14   Sadia Khatun
16    Tania Akter
18     Faria Noor
19   Sabbir Ahmed

**c. More filters by using conditions:**

**Not equal:**

In [174]:
df[df["City"] != "Dhaka"]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80.0,80,1788888888,ray@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,93.0,96,1700000000,leo@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,NaN,80,1733300003,priya@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,NaN,70,1766600006,arif@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,79.0,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com

**Opposite:**

In [177]:
df[~(df['Gender'] == "M")]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
8,109,Nina Begum,F,24,Dhaka,EEE,73,C,7000,True,2022-03-10,NaN,78,1799999999,nina@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,70.0,65,1711100001,riya@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,NaN,80,1733300003,priya@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com

In [181]:
df[df["Score"].between(87, 90)]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com

**isin() :**

In [183]:
df[df["City"].isin(["Dhaka", "London"])]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
5,106,Tom Hasan,M,26,Dhaka,CSE,70,C,5000,True,2022-01-15,NaN,72,1766666666,tom@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80.0,80,1788888888,ray@gmail.com
8,109,Nina Begum,F,24,Dhaka,EEE,73,C,7000,True,2022-03-10,NaN,78,1799999999,nina@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,70.0,65,1711100001,riya@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,NaN,80,1733300003,priya@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,NaN,70,1766600006,arif@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

**c. Query Method:** Advanced

In [ ]:
df.query("Score > 80 and Department == 'EEE'")

**7. Cleaning Data   → null values, duplicate rows, data types, Inconsistent text.**

**a. Missing Value (NaN) :** 
          
          .isnull().sum()
          .dropna()
          .fillna()

**To check in columns:**

In [186]:
df.isnull().sum()

StudentID     0
Name          0
Gender        0
Age           0
City          0
Department    0
Score         0
Grade         0
Fee           0
Paid          0
JoinDate      0
Marks         5
Attendance    0
Phone         0
Email         0
dtype: int64

**To check NaN in rows:**

In [187]:
df[df["Marks"].isnull()]

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,NaN,85,1733333333,sara@gmail.com
5,106,Tom Hasan,M,26,Dhaka,CSE,70,C,5000,True,2022-01-15,NaN,72,1766666666,tom@gmail.com
8,109,Nina Begum,F,24,Dhaka,EEE,73,C,7000,True,2022-03-10,NaN,78,1799999999,nina@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,NaN,80,1733300003,priya@gmail.com
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,NaN,70,1766600006,arif@gmail.com

**b. Duplicate Rows:**
           
           .dropna()
           .dropna(axis=1)
           .dropna(subset=["column_name"])

**Drop any row that has NaN:**

In [188]:
df.dropna()

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80.0,80,1788888888,ray@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,93.0,96,1700000000,leo@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,70.0,65,1711100001,riya@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,79.0,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

**Drop specific mentioned column's null:**

In [189]:
df.dropna(subset=["Marks"])

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Marks,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,88.0,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,92.0,95,1722222222,bob@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,95.0,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,85.0,88,1755555555,mia@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,97.0,99,1777777777,emma@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80.0,80,1788888888,ray@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,93.0,96,1700000000,leo@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,70.0,65,1711100001,riya@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,90.0,91,1722200002,karim@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,96.0,97,1744400004,nabil@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,84.0,87,1755500005,sadia@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,93.0,94,1777700007,tania@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,79.0,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,88.0,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,95.0,98,1700000010,sabbir@gmail.com

In [190]:
df.dropna(axis=1)

,StudentID,Name,Gender,Age,City,Department,Score,Grade,Fee,Paid,JoinDate,Attendance,Phone,Email
0,101,Ali Ahmed,M,22,Dhaka,CSE,85,B,5000,True,2022-01-15,90,1711111111,ali@gmail.com
1,102,Bob Khan,M,25,London,BBA,90,A,6000,True,2021-06-20,95,1722222222,bob@gmail.com
2,103,Sara Islam,F,23,Dhaka,CSE,78,C,5000,False,2022-03-10,85,1733333333,sara@gmail.com
3,104,John Doe,M,24,Paris,EEE,92,A,7000,True,2020-09-01,98,1744444444,john@gmail.com
4,105,Mia Rahman,F,22,London,BBA,88,B,6000,False,2021-11-25,88,1755555555,mia@gmail.com
5,106,Tom Hasan,M,26,Dhaka,CSE,70,C,5000,True,2022-01-15,72,1766666666,tom@gmail.com
6,107,Emma Akter,F,23,Paris,EEE,95,A,7000,True,2020-09-01,99,1777777777,emma@gmail.com
7,108,Ray Molla,M,25,London,BBA,80,B,6000,False,2021-06-20,80,1788888888,ray@gmail.com
8,109,Nina Begum,F,24,Dhaka,EEE,73,C,7000,True,2022-03-10,78,1799999999,nina@gmail.com
9,110,Leo Chowdhury,M,22,Paris,CSE,91,A,5000,True,2020-09-01,96,1700000000,leo@gmail.com
10,111,Riya Sen,F,21,Dhaka,BBA,67,C,6000,False,2023-01-10,65,1711100001,riya@gmail.com
11,112,Karim Uddin,M,27,Paris,EEE,88,B,7000,True,2019-08-15,91,1722200002,karim@gmail.com
12,113,Priya Das,F,22,London,CSE,76,C,5000,True,2022-07-20,80,1733300003,priya@gmail.com
13,114,Nabil Islam,M,24,Dhaka,BBA,94,A,6000,True,2021-03-05,97,1744400004,nabil@gmail.com
14,115,Sadia Khatun,F,23,Paris,CSE,82,B,5000,False,2022-09-12,87,1755500005,sadia@gmail.com
15,116,Arif Hossain,M,25,London,EEE,69,C,7000,True,2021-05-18,70,1766600006,arif@gmail.com
16,117,Tania Akter,F,22,Dhaka,BBA,91,A,6000,True,2022-02-28,94,1777700007,tania@gmail.com
17,118,Rakib Hassan,M,23,Paris,CSE,77,C,5000,False,2022-11-01,75,1788800008,rakib@gmail.com
18,119,Faria Noor,F,26,London,EEE,86,B,7000,True,2020-04-14,89,1799900009,faria@gmail.com
19,120,Sabbir Ahmed,M,21,Dhaka,BBA,93,A,6000,True,2023-03-22,98,1700000010,sabbir@gmail.com

c. Fill :
    
    .fillna()
    .fillna(Method="ffill")
    .fillna(Method="bfill")

In [ ]:
df.

8. Sorting         → sort_values(), sort_index()


9. Grouping        → groupby()y/Map      → apply(), map(), lambda
12. Time Series    → date-based analysis
13. Export Data    → to_csv(), to_exce
10. Merging        → merge(), concat(), join()
11. Appll()